version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: srms_backend
    ports:
      - "5001:5001"
    environment:
      DATABASE_URL: mssql://sa:Rfx14w.14w.@10.0.1.90:1433/srms_db
      PORT: 5001
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: srms_frontend
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:5001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
